USE mahudent_db;
DELETE FROM catalogo_tratamientos WHERE nombre LIKE '%Ã%';
INSERT IGNORE INTO catalogo_tratamientos (nombre, precio_base, categoria, estado_odontograma) VALUES 
('Endodoncia Incisivo Central', 150.00, 'Endodoncia', NULL),
('Endodoncia Incisivo Lateral', 150.00, 'Endodoncia', NULL),
('Endodoncia Premolar', 200.00, 'Endodoncia', NULL),
('Endodoncia Molar', 300.00, 'Endodoncia', NULL),
('Perno de Fibra de Vidrio', 100.00, 'Endodoncia', NULL),
('Curación Simple', 80.00, 'Restauración', 'resina'),
('Curación Compuesta', 120.00, 'Restauración', 'resina'),
('Curación Compleja', 150.00, 'Restauración', 'resina'),
('Profilaxis', 50.00, 'Prevención', NULL),
('Flúor Barniz', 40.00, 'Prevención', NULL),
('Flúor Gel', 30.00, 'Prevención', NULL),
('Carillas de Resina', 200.00, 'Estética', NULL),
('Carillas de Porcelana', 400.00, 'Estética', NULL),
('Carillas de Zirconio', 500.00, 'Estética', NULL),
('Corona de Zirconio', 600.00, 'Prótesis Fija', 'corona'),
('Corona de Porcelana', 400.00, 'Prótesis Fija', 'corona'),
('Corona Disilicato', 500.00, 'Prótesis Fija', 'corona'),
('Corona Metal Porcelana', 350.00, 'Prótesis Fija', 'corona'),
('Prótesis Parcial', 400.00, 'Prótesis Removible', NULL),
('Prótesis Total', 600.00, 'Prótesis Removible', NULL),
('Prótesis Flexible', 550.00, 'Prótesis Removible', NULL),
('Extracción Incisivo', 60.00, 'Cirugía', 'ausente'),
('Extracción Premolar', 80.00, 'Cirugía', 'ausente'),
('Extracción Molar', 100.00, 'Cirugía', 'ausente'),
('Extracción Tercera', 150.00, 'Cirugía', 'ausente'),
('Retenedores Removibles', 150.00, 'Ortodoncia', NULL),
('Retenedores Fijos', 180.00, 'Ortodoncia', NULL),
('Placa', 200.00, 'Ortodoncia', NULL),
('Férula Miorelajante', 250.00, 'Oclusión', NULL),

('Cepillo Medio', 15.00, 'Insumos', NULL),
('Cepillo Duro', 15.00, 'Insumos', NULL),
('Cepillo Suave', 15.00, 'Insumos', NULL),
('Cepillo Ortodontico', 20.00, 'Insumos', NULL),
('Cepillo Encías', 18.00, 'Insumos', NULL),
('Interprox Conical', 22.00, 'Insumos', NULL),
('Interprox MicroInterprox', 22.00, 'Insumos', NULL),
('Super Hilo Dental', 12.00, 'Insumos', NULL),
('Cera Ortodontica', 10.00, 'Insumos', NULL),
('Pasta Ortodontica', 25.00, 'Insumos', NULL),
('Pasta Aloe', 20.00, 'Insumos', NULL),
('Pasta Encías', 28.00, 'Insumos', NULL),
('Pasta Sensible', 25.00, 'Insumos', NULL),
('Pasta Blanqueadora', 30.00, 'Insumos', NULL),
('Pasta CPC', 25.00, 'Insumos', NULL),
('Enjuague Encías 500ml', 40.00, 'Insumos', NULL),
('Enjuague Encías 150ml', 25.00, 'Insumos', NULL),
('Enjuague CPC', 35.00, 'Insumos', NULL),
('Enjuague Ortodontico', 35.00, 'Insumos', NULL),
('Enjuague Sensible', 35.00, 'Insumos', NULL),
('Enjuague Halita', 45.00, 'Insumos', NULL),
('Perio-AID Active', 40.00, 'Insumos', NULL),
('PerioAID Intensive', 42.00, 'Insumos', NULL),
('Cepillo Vitis Junior', 18.00, 'Insumos', NULL),
('Cepillo Vitis Kids', 18.00, 'Insumos', NULL),
('Cepillo Vitis Junior Gel', 20.00, 'Insumos', NULL),
('Vitis Kids Gel', 20.00, 'Insumos', NULL);
