SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE catalogo_tratamientos;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO catalogo_tratamientos (nombre, precio_base, categoria, estado_odontograma) VALUES 
('Resina Simple', 80.00, 'Restauración', 'resina'),
('Resina Compuesta', 120.00, 'Restauración', 'resina'),
('Curación Simple', 80.00, 'Restauración', 'resina'),
('Curación Compuesta', 120.00, 'Restauración', 'resina'),
('Curación Compleja', 150.00, 'Restauración', 'resina'),
('Incrustación Dental', 250.00, 'Restauración', 'corona'),
('Endodoncia Anterior', 200.00, 'Endodoncia', NULL),
('Endodoncia Premolar', 250.00, 'Endodoncia', NULL),
('Endodoncia Molar', 350.00, 'Endodoncia', NULL),
('Endodoncia Incisivo Central', 150.00, 'Endodoncia', NULL),
('Endodoncia Incisivo Lateral', 150.00, 'Endodoncia', NULL),
('Perno de Fibra de Vidrio', 100.00, 'Endodoncia', NULL),
('Limpieza Dental', 50.00, 'Prevención', NULL),
('Profilaxis', 50.00, 'Prevención', NULL),
('Flúor Barniz', 40.00, 'Prevención', NULL),
('Flúor Gel', 30.00, 'Prevención', NULL),
('Blanqueamiento', 200.00, 'Estética', NULL),
('Carillas de Resina', 200.00, 'Estética', NULL),
('Carillas de Porcelana', 400.00, 'Estética', NULL),
('Carillas de Zirconio', 500.00, 'Estética', NULL),
('Corona Dental', 350.00, 'Prótesis Fija', 'corona'),
('Corona de Zirconio', 600.00, 'Prótesis Fija', 'corona'),
('Corona de Porcelana', 400.00, 'Prótesis Fija', 'corona'),
('Corona Disilicato', 500.00, 'Prótesis Fija', 'corona'),
('Corona Metal Porcelana', 350.00, 'Prótesis Fija', 'corona'),
('Prótesis Parcial', 400.00, 'Prótesis Removible', NULL),
('Prótesis Total', 600.00, 'Prótesis Removible', NULL),
('Prótesis Flexible', 550.00, 'Prótesis Removible', NULL),
('Extracción Simple', 60.00, 'Cirugía', 'ausente'),
('Extracción Quirúrgica', 150.00, 'Cirugía', 'ausente'),
('Extracción Incisivo', 60.00, 'Cirugía', 'ausente'),
('Extracción Premolar', 80.00, 'Cirugía', 'ausente'),
('Extracción Molar', 100.00, 'Cirugía', 'ausente'),
('Extracción Tercera', 150.00, 'Cirugía', 'ausente'),
('Implante Dental', 800.00, 'Implantología', NULL),
('Ortodoncia - Brackets', 2500.00, 'Ortodoncia', NULL),
('Retenedores Removibles', 150.00, 'Ortodoncia', NULL),
('Retenedores Fijos', 180.00, 'Ortodoncia', NULL),
('Placa', 200.00, 'Ortodoncia', NULL),
('Férula Miorelajante', 250.00, 'Oclusión', NULL),
('Radiografía Periapical', 15.00, 'Diagnóstico', NULL),
('Radiografía Panorámica', 40.00, 'Diagnóstico', NULL),
('Cepillo Medio', 15.00, 'Insumos', NULL),
('Cepillo Duro', 15.00, 'Insumos', NULL),
('Cepillo Suave', 15.00, 'Insumos', NULL),
('Cepillo Ortodontico', 20.00, 'Insumos', NULL),
('Cepillo Encías', 18.00, 'Insumos', NULL),
('Interprox Conical', 22.00, 'Insumos', NULL),
('Interprox MicroInterprox', 22.00, 'Insumos', NULL),
('Super Hilo Dental', 12.00, 'Insumos', NULL),
('Cera Ortodontica', 10.00, 'Insumos', NULL),
('Pasta Ortodontica', 25.00, 'Insumos', NULL),
('Pasta Aloe', 20.00, 'Insumos', NULL),
('Pasta Encías', 28.00, 'Insumos', NULL),
('Pasta Sensible', 25.00, 'Insumos', NULL),
('Pasta Blanqueadora', 30.00, 'Insumos', NULL),
('Pasta CPC', 25.00, 'Insumos', NULL),
('Enjuague Encías 500ml', 40.00, 'Insumos', NULL),
('Enjuague Encías 150ml', 25.00, 'Insumos', NULL),
('Enjuague CPC', 35.00, 'Insumos', NULL),
('Enjuague Ortodontico', 35.00, 'Insumos', NULL),
('Enjuague Sensible', 35.00, 'Insumos', NULL),
('Enjuague Halita', 45.00, 'Insumos', NULL),
('Perio-AID Active', 40.00, 'Insumos', NULL),
('PerioAID Intensive', 42.00, 'Insumos', NULL),
('Cepillo Vitis Junior', 18.00, 'Insumos', NULL),
('Cepillo Vitis Kids', 18.00, 'Insumos', NULL),
('Cepillo Vitis Junior Gel', 20.00, 'Insumos', NULL),
('Vitis Kids Gel', 20.00, 'Insumos', NULL);
